### ISSUE TITLE
Unable to Load ts3server.ini and Can't Adjust Configuration

### ISSUE THREAD

**Issue by backlands** [ich777/docker-teamspeak#1]
I was working on getting a container running using this image however it appears that the ts3server.ini file is not actually passed to the server start script. Maybe I am missing something but it appears that in scripts/start-server.sh on line 102 you have: `${DATA_DIR}/ts3server`. Typically with TS3 in order to read the ts3server.ini file you need to specify the `inifile` parameter.

No matter how I attempt to change the settings it does not load the ts3server.ini file. Let me know if I am missing a step or something as that could be the case here!

**Comment by ich777** [comment]
Sorry, I somehow completely missed that issue. I assume you are now using a different container or the problem is solved.
Feel free to open up a new issue if you still want to use that image or experiencing further issues.

**Comment by backlands** [comment]
No worries, you are correct I ended up migrating over to `fithwum/teamspeak-server` which supported what I needed and worked for me for a very long time. Recently shut down all my TeamSpeak servers though so now it is completely unneeded by me. Thanks for the follow up, appreciate all the hard work you do on all these images!

**Comment by ich777** [comment]
Really, the container should have supported this since you could pass over the argument.

I'm still running two TS3 servers over here. :)
